# This file was generated by GoReleaser. DO NOT EDIT.
class Jargon < Formula
  desc "Text pipelines for CLI and Go."
  homepage "https://github.com/clipperhouse/jargon"
  version "0.9.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/clipperhouse/jargon/releases/download/v0.9.12/jargon_0.9.12_Darwin_x86_64.tar.gz"
    sha256 "eb87b153feeeebcaff0aba943cda8c4fd47a4b714a2c934e156a92131cfbead3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/clipperhouse/jargon/releases/download/v0.9.12/jargon_0.9.12_Linux_x86_64.tar.gz"
      sha256 "381d3c1f35e0a8b8c08cd5dbc2b29c3b5395553ad9e030c6b303f89bf1d86215"
    end
  end

  def install
    bin.install "jargon"
  end
end
