# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Words < Formula
  desc "A command-line utility for splitting words by the Unicode standard"
  homepage "https://github.com/clipperhouse/words"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/clipperhouse/words/releases/download/v0.3.0/words_0.3.0_Darwin_arm64.tar.gz"
      sha256 "0573072705ecdea9cecd3c0a2cf59122e889fb7f8236a613f87e43c257fe38f4"

      def install
        bin.install "words"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clipperhouse/words/releases/download/v0.3.0/words_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "178510548044b96417639e82a679352b105689eb5e7b1d07baf4260d312c4a6a"

      def install
        bin.install "words"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clipperhouse/words/releases/download/v0.3.0/words_0.3.0_Linux_x86_64.tar.gz"
      sha256 "0dc272909750430d32c1cf1b3a642c89232598bffaf5ed81150fae8d2c5403ce"

      def install
        bin.install "words"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clipperhouse/words/releases/download/v0.3.0/words_0.3.0_Linux_arm64.tar.gz"
      sha256 "d503b0e437921d43552254cfedd5f5580793bf3c802ed22b9dc8111f2b83dcd9"

      def install
        bin.install "words"
      end
    end
  end
end
